# Generated by Django 5.1.2 on 2024-10-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='propetaries',
            field=models.IntegerField(null=True),
        ),
    ]
